apiVersion: v1
kind: Pod
metadata:
  name: usrp-test
  annotations:
    k8s.v1.cni.cncf.io/networks: p4-macvlan-gnb
  labels:
    app: usrptest
spec:
  containers:
  - image: vinodkhandkar/kaida:sopnode-usrp-net-test-ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: busybox
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME", "NET_RAW"]
  restartPolicy: Always
